version: '3.8'
services:
  server:
    build: ./server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    container_name: api_c
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://simon:example_password@db:5432/phonebook_db
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=simon
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=phonebook_db

volumes:
  postgres_data: